# Generated by Django 5.2.9 on 2026-06-11 12:27

from django.db import migrations, models

import wagtail_block_fields.fields


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "colors",
                    wagtail_block_fields.fields.MultipleChoiceField(
                        blank=True,
                        choices=[("red", "Red"), ("green", "Green"), ("blue", "Blue")],
                        null=True,
                    ),
                ),
                (
                    "info",
                    wagtail_block_fields.fields.StructField(
                        [("label", 0), ("tags", 1)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.MultipleChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("red", "Red"),
                                        ("green", "Green"),
                                        ("blue", "Blue"),
                                    ]
                                },
                            ),
                        },
                        null=True,
                    ),
                ),
            ],
        ),
    ]
